user nginx;
worker_processes auto;

error_log /dev/null crit;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # 通常のアクセスログは保存しない
    # Timexeed独自のAPI操作ログとは別物
    access_log off;

    sendfile on;
    keepalive_timeout 65;
    server_tokens off;

    client_max_body_size 20m;

    include /etc/nginx/conf.d/*.conf;
}